# Generated by Django 3.1.6 on 2021-03-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='greeting',
            field=models.TextField(max_length=255),
        ),
    ]
