# Generated by Django 3.1.6 on 2021-03-26 02:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210326_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'プロフィール', 'verbose_name_plural': 'プロフィール'},
        ),
        migrations.AddField(
            model_name='profile',
            name='regist_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 2, 33, 11, 859892, tzinfo=utc)),
        ),
    ]
