# Generated by Django 3.1.6 on 2021-03-26 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210326_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='regist_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
