# Generated by Django 3.1.6 on 2021-03-26 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '記事', 'verbose_name_plural': '記事'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': '写真', 'verbose_name_plural': '写真'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_image', to='users.article'),
        ),
    ]
