# Generated by Django 3.1.6 on 2021-04-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210402_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/no_image_face.png', null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
