# Generated by Django 3.1.6 on 2021-04-19 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210417_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'アルバム',
                'verbose_name_plural': 'アルバム',
            },
        ),
    ]
