# Generated by Django 3.1.6 on 2021-04-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
