# Generated by Django 3.1.6 on 2021-04-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='tagged_art', to='users.Article'),
        ),
    ]
