# Generated by Django 3.1.6 on 2021-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='greeting',
            field=models.TextField(max_length=1000),
        ),
    ]
