# Generated by Django 3.1.6 on 2021-04-28 05:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20210427_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ability_power',
            field=models.IntegerField(default=0, validators=[users.models.check_ability]),
        ),
    ]
