# Generated by Django 3.1.6 on 2021-04-28 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20210428_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ability_power',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
