# Generated by Django 3.1.6 on 2021-04-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210428_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ability_power',
            field=models.IntegerField(default=0),
        ),
    ]
