# Generated by Django 3.1.6 on 2021-04-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20210428_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=models.TextField(max_length=100),
        ),
    ]
