# Generated by Django 3.1.6 on 2021-05-04 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=500)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_image', to='users.photo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_writed_tag', to='users.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_detail_write_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'タグ詳細',
                'verbose_name_plural': 'タグ詳細',
            },
        ),
    ]
