# Generated by Django 3.1.6 on 2021-05-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_tagdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagdetail',
            name='tag_str',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tagdetail',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_writed_tag', to='users.tag'),
        ),
    ]
